const { Sequelize, DataTypes } = require('sequelize');

/**
 * CallSummary model — stores summaries generated by the AI Call Assistant (Busy Mode).
 */
const CallSummary = (sequelize) => {
  return sequelize.define('CallSummary', {
    id: {
      type: DataTypes.UUID,
      defaultValue: Sequelize.UUIDV4,
      primaryKey: true,
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: { model: 'users', key: 'id' },
    },
    callerName: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    callerNumber: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    reason: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    urgency: {
      type: DataTypes.ENUM('low', 'medium', 'high', 'emergency'),
      defaultValue: 'low',
    },
    callbackRequested: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    notes: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.NOW,
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.NOW,
    },
  }, {
    tableName: 'call_summaries',
    timestamps: true,
  });
};

module.exports = CallSummary;
